In [16]:
from sklearn.tree import DecisionTreeClassifier 
from MyDatasetLoader import MyDatasetLoader
from sklearn.decomposition import PCA
from sklearn import metrics
import torch

def reduce_dim_pca(dataset,reduce_dim_to):
    pca = PCA(n_components=reduce_dim_to)
    x= pca.fit_transform(dataset[0].x)
   
    dataset.data.x =torch.tensor(x,dtype=torch.float32)
    return 
dataset=MyDatasetLoader(root='./cora')
reduce_dim_pca(dataset,100)

train_x= dataset[0].x[dataset[0].train_mask]
train_y= dataset[0].y[dataset[0].train_mask]
test_x = dataset[0].x[dataset[0].test_mask]
test_y = dataset[0].y[dataset[0].test_mask]


len(train_x[0])


Processing...
Done!


100

In [20]:
train_x= dataset[0].x
train_y= dataset[0].y
test_x = dataset[0].x
test_y = dataset[0].y

In [21]:
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(train_x,train_y)
y_pred = clf.predict(test_x)
print("Accuracy:",metrics.accuracy_score(test_y, y_pred))
print("f1:",metrics.f1_score(test_y, y_pred,average='macro'))
print(dataset.data.label_map)
print("confusion matrix:\n",metrics.confusion_matrix(test_y, y_pred))

Accuracy: 0.7200886262924667
f1: 0.7364503248546261
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[818   0   0   0   0   0   0]
 [ 83  97   0   0   0   0   0]
 [ 91   0 126   0   0   0   0]
 [179   0   0 247   0   0   0]
 [137   0   0   0 214   0   0]
 [165   0   0   0   0 253   0]
 [103   0   0   0   0   0 195]]


In [22]:
y_pred = clf.predict(train_x)
print("Accuracy:",metrics.accuracy_score(train_y, y_pred))
print("Accuracy:",metrics.accuracy_score(train_y, y_pred))
print("f1:",metrics.f1_score(train_y, y_pred,average='macro'))
print(dataset.data.label_map)
print("confusion matrix:\n",metrics.confusion_matrix(train_y, y_pred))

Accuracy: 0.7200886262924667
Accuracy: 0.7200886262924667
f1: 0.7364503248546261
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[818   0   0   0   0   0   0]
 [ 83  97   0   0   0   0   0]
 [ 91   0 126   0   0   0   0]
 [179   0   0 247   0   0   0]
 [137   0   0   0 214   0   0]
 [165   0   0   0   0 253   0]
 [103   0   0   0   0   0 195]]


In [23]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=20)
clf = clf.fit(train_x,train_y)
y_pred = clf.predict(test_x)
print("Accuracy:",metrics.accuracy_score(test_y, y_pred))
print("Accuracy:",metrics.accuracy_score(test_y, y_pred))
print("f1:",metrics.f1_score(test_y, y_pred,average='macro'))
print(dataset.data.label_map)
print("confusion matrix:\n",metrics.confusion_matrix(test_y, y_pred))

Accuracy: 0.7200886262924667
Accuracy: 0.7200886262924667
f1: 0.7364503248546261
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[818   0   0   0   0   0   0]
 [ 83  97   0   0   0   0   0]
 [ 91   0 126   0   0   0   0]
 [179   0   0 247   0   0   0]
 [137   0   0   0 214   0   0]
 [165   0   0   0   0 253   0]
 [103   0   0   0   0   0 195]]


In [24]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf = clf.fit(train_x,train_y)
y_pred = clf.predict(test_x)
print("Accuracy:",metrics.accuracy_score(test_y, y_pred))
print("f1:",metrics.f1_score(test_y, y_pred,average='macro'))
print(dataset.data.label_map)
print("confusion matrix:\n",metrics.confusion_matrix(test_y, y_pred))

Accuracy: 0.7200886262924667
f1: 0.7364503248546261
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[818   0   0   0   0   0   0]
 [ 83  97   0   0   0   0   0]
 [ 91   0 126   0   0   0   0]
 [179   0   0 247   0   0   0]
 [137   0   0   0 214   0   0]
 [165   0   0   0   0 253   0]
 [103   0   0   0   0   0 195]]
