In [6]:

import sklearn
from sklearn.decomposition import PCA
from MyDatasetLoader import MyDatasetLoader
import torch
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

def reduce_dim_pca(dataset,reduce_dim_to):
    pca = PCA(n_components=reduce_dim_to)
    x= pca.fit_transform(dataset[0].x)
   
    dataset.data.x =torch.tensor(x,dtype=torch.float32)
    return 


In [2]:
dataset=MyDatasetLoader(root='./cora')
#reduce_dim_pca(dataset,100)

train_x= dataset[0].x[dataset[0].train_mask]
train_y= dataset[0].y[dataset[0].train_mask]
test_x = dataset[0].x[dataset[0].test_mask]
test_y = dataset[0].y[dataset[0].test_mask]
len(train_x[0])


Processing...
Done!


1433

In [18]:
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(train_x,train_y)
predicted= clf.predict(test_x)
y_pred = clf.predict(test_x)
print("Accuracy:",metrics.accuracy_score(test_y, y_pred))
print("f1:",metrics.f1_score(test_y, y_pred,average='macro'))
print(dataset.data.label_map)
print("confusion matrix:\n",metrics.confusion_matrix(test_y, y_pred))


Accuracy: 0.2829028290282903
f1: 0.06300506779893165
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[230   0   0   0   0   0   0]
 [ 47   0   0   0   0   0   0]
 [ 71   0   0   0   0   0   0]
 [143   0   0   0   0   0   0]
 [100   0   0   0   0   0   0]
 [128   0   0   0   0   0   0]
 [ 94   0   0   0   0   0   0]]
