In [2]:
from sklearn.linear_model import LogisticRegression
import sklearn
from MyDatasetLoader import MyDatasetLoader
from sklearn.decomposition import PCA
from sklearn import metrics
import torch


def reduce_dim_pca(dataset,reduce_dim_to):
    pca = PCA(n_components=reduce_dim_to)
    x= pca.fit_transform(dataset[0].x)
   
    dataset.data.x =torch.tensor(x,dtype=torch.float32)
    return 
dataset=MyDatasetLoader(root='./cora')
reduce_dim_pca(dataset,100)

train_x= dataset[0].x[dataset[0].train_mask]
train_y= dataset[0].y[dataset[0].train_mask]
test_x = dataset[0].x[dataset[0].test_mask]
test_y = dataset[0].y[dataset[0].test_mask]




Processing...
Done!


In [6]:
clf = LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='l2', C=1.0)
clf.fit(train_x,train_y)
clf = clf.fit(train_x,train_y)
y_pred = clf.predict(test_x)
print("Accuracy:",metrics.accuracy_score(test_y, y_pred))
print("f1:",metrics.f1_score(test_y, y_pred,average='macro'))
print(dataset.data.label_map)
print("confusion matrix:\n",metrics.confusion_matrix(test_y, y_pred))

Accuracy: 0.2939729397293973
f1: 0.06491037479630636
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[239   0   0   0   0   0   0]
 [ 69   0   0   0   0   0   0]
 [ 80   0   0   0   0   0   0]
 [132   0   0   0   0   0   0]
 [101   0   0   0   0   0   0]
 [117   0   0   0   0   0   0]
 [ 75   0   0   0   0   0   0]]


In [7]:
clf = clf.fit(train_x,train_y)
y_pred = clf.predict(train_x)
print("Accuracy:",metrics.accuracy_score(train_y, y_pred))
print("f1:",metrics.f1_score(train_y, y_pred,average='macro'))
print(dataset.data.label_map)
print("confusion matrix:\n",metrics.confusion_matrix(train_y, y_pred))

Accuracy: 0.8344615384615385
f1: 0.8234760860787002
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[436   3   6  23  16   3   6]
 [  6  65   1   2  11   1  11]
 [  8   0 105   0   5   6   2]
 [ 33   0   1 204   5   1   3]
 [ 26   5   2   7 163   3   8]
 [ 16   2   4   3   0 227   1]
 [ 14   3   2   4  12   4 156]]
