In [33]:
from MyDatasetLoader import MyDatasetLoader
from sklearn import svm
from sklearn.decomposition import PCA
from MyDatasetLoader import MyDatasetLoader
import torch
import matplotlib.pyplot as plt
from sklearn import metrics
import numpy as np
from sklearn import model_selection

def reduce_dim_pca(dataset,reduce_dim_to):
    pca = PCA(n_components=reduce_dim_to)
    x= pca.fit_transform(dataset[0].x)
   
    dataset.data.x =torch.tensor(x,dtype=torch.float32)
    return 

dataset=MyDatasetLoader(root='./cora')
#reduce_dim_pca(dataset,100)

train_x= dataset[0].x[dataset[0].train_mask]
train_y= dataset[0].y[dataset[0].train_mask]
test_x = dataset[0].x[dataset[0].test_mask]
test_y = dataset[0].y[dataset[0].test_mask]
val_x =dataset[0].x[dataset[0].val_mask]
val_y =dataset[0].y[dataset[0].val_mask]
len(train_x[0])



Processing...
Done!


1433

In [34]:
clf = svm.SVC(kernel='linear') 
clf = clf.fit(train_x,train_y)
y_pred = clf.predict(val_x)
print("Accuracy:",metrics.accuracy_score(val_y, y_pred))
print("f1:",metrics.f1_score(val_y, y_pred,average='macro'))
print(dataset.data.label_map)
print("confusion matrix:\n",metrics.confusion_matrix(val_y, y_pred))

Accuracy: 0.31851851851851853
f1: 0.06902086677367578
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[86  0  0  0  0  0  0]
 [14  0  0  0  0  0  0]
 [11  0  0  0  0  0  0]
 [47  0  0  0  0  0  0]
 [36  0  0  0  0  0  0]
 [48  0  0  0  0  0  0]
 [28  0  0  0  0  0  0]]


In [35]:

# fit the model
fignum = 1
for kern in ("linear", "poly", "rbf"):
    clf = svm.SVC(kernel=kern) 
    clf = clf.fit(train_x,train_y)
    y_pred = clf.predict(train_x)
    print("Accuracy:",metrics.accuracy_score(train_y, y_pred))
    print("f1:",metrics.f1_score(train_y, y_pred,average='macro'))
    print(dataset.data.label_map)
    print("confusion matrix:\n",metrics.confusion_matrix(train_y, y_pred))
    

Accuracy: 0.9981538461538462
f1: 0.9981823724365787
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[493   0   0   0   0   0   0]
 [  0  97   0   0   0   0   0]
 [  1   0 125   0   0   0   0]
 [  0   0   0 247   0   0   0]
 [  1   0   0   1 212   0   0]
 [  0   0   0   0   0 253   0]
 [  0   0   0   0   0   0 195]]
Accuracy: 0.8898461538461538
f1: 0.9042984576138247
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[493   0   0   0   0   0   0]
 [ 20  77   0   0   0   0   0]
 [ 14   0 112   0   0   0   0]
 [ 38   0   0 209   0   0   0]
 [ 31   0   0   0 183   0   0]
 [ 50   0   0   0   0 203   0]
 [ 26   0   0   0   0   0 169]]
Accuracy: 0.9556923076923077
f1: 0.9604114646063069
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Le

In [36]:

# fit the model
fignum = 1
for kern in ["linear", "poly", "rbf"]:
    clf = svm.SVC(kernel=kern) 
    clf = clf.fit(train_x,train_y)
    y_pred = clf.predict(test_x)
    print(kern)
    print("Accuracy:",metrics.accuracy_score(test_y, y_pred))
    print("f1:",metrics.f1_score(test_y, y_pred,average='macro'))
    print(dataset.data.label_map)
    print("confusion matrix:\n",metrics.confusion_matrix(test_y, y_pred))

linear
Accuracy: 0.2939729397293973
f1: 0.06491037479630636
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[239   0   0   0   0   0   0]
 [ 69   0   0   0   0   0   0]
 [ 80   0   0   0   0   0   0]
 [132   0   0   0   0   0   0]
 [101   0   0   0   0   0   0]
 [117   0   0   0   0   0   0]
 [ 75   0   0   0   0   0   0]]
linear
Accuracy: 0.2939729397293973
f1: 0.06491037479630636
{'Neural_Networks': 0, 'Rule_Learning': 1, 'Reinforcement_Learning': 2, 'Probabilistic_Methods': 3, 'Theory': 4, 'Genetic_Algorithms': 5, 'Case_Based': 6}
confusion matrix:
 [[239   0   0   0   0   0   0]
 [ 69   0   0   0   0   0   0]
 [ 80   0   0   0   0   0   0]
 [132   0   0   0   0   0   0]
 [101   0   0   0   0   0   0]
 [117   0   0   0   0   0   0]
 [ 75   0   0   0   0   0   0]]
linear
Accuracy: 0.2939729397293973
f1: 0.06491037479630636
{'Neural_Networks': 0, 'Rule_Learnin